services:
  postgres:
    image: postgres:16
    container_name: sole8_postgres
    restart: always
    environment:
      POSTGRES_USER: sole8
      POSTGRES_PASSWORD: sole8pwd
      POSTGRES_DB: sole8_db
      PGDATABASE: sole8_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sole8"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sole8_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5295:5295"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5295"
